# Generated by Django 3.1.7 on 2021-03-14 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=100)),
                ('criado_em', models.DateTimeField(verbose_name='data_criacao')),
            ],
        ),
    ]
